### PR TITLE
htmlEncode escapes only string values

### PR DESCRIPTION
**Pull request by kasparsklavins**
## Scope
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made (this change is also documented in the [change log](https://github.com/kartik-v/yii2-editable/blob/master/CHANGE.md)):

- Does not try to escape html entities (<, >, ", ') on non-string values in `htmlEncode`. Not documented.

### CODE REVIEW

**Comment by kasparsklavins** [comment]
Are `.min` files updated automatically?

**Comment by kartik-v** [comment]
- Need to understand this correct. There is a validation condition for `data` as an object before the test you have already and the other condition should normally result in string. Why do you feel `typeof data === "string"` test is needed? Do you have any other type of data?

- You can minify the JS files [from here](http://refresh-sf.com/) and submit.

**Comment by kasparsklavins** [comment]
When using in combination with select2, and removing all selected options, `$input.value` is undefined. So, a defined value is passed from here https://github.com/kartik-v/yii2-editable/blob/master/src/assets/js/editable.js#L201 and `replace` does not exist on `undefined`

I'll minify the file if no further changes are needed.

**Comment by kasparsklavins** [comment]
> You can minify the JS files [from here](http://refresh-sf.com/) and submit.

k

**Pull request closed without merging**
